/**
 * Copyright (c) 2022-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ComponentConfig {
  public WH_100_100 = '100%';
  public WH_30_100 = '30%';
  public WH_33_100 = '33%';
  public WH_35_100 = '35%';
  public WH_40_100 = '40%';
  public WH_45_100 = '45%';
  public WH_50_100 = '50%';
  public WH_55_100 = '55%';
  public WH_83_100 = '83%';
  public WH_90_100 = '90%';
  public value_20 = 20;
  public font_20 = 20;
  public MAX_LINES_1 = 1;
  public MAX_LINES_2 = 2;
  public MAX_LINES_3 = 3;
  public DURATION_TIME = 200;
}

let componentConfig = new ComponentConfig();

export default componentConfig as ComponentConfig;