/**
 * Copyright (c) 2024-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum NavEntryKey {
  HOME_ENTRY = 'home_page',
  CA_CERTIFICATE_ENTRY = 'ca_cert',
  CREDENTIAL_LIST_ENTRY = 'cred_list',
  INSTALL_ENTRY = 'install_from_storage',
  CA_SYSTEM_DETAIL_ENTRY = 'ca_system_detail',
  CA_USER_DETAIL_ENTRY = 'ca_user_detail',
  CRED_SYSTEM_DETAIL_ENTRY = 'cred_system_detail',
  CRED_USER_DETAIL_ENTRY = 'cred_user_detail',
  AUTHORIZED_APP_ENTRY = 'authorized_app_management',
  CRED_PWD_INPUT_ENTRY = 'cred_pwd_input',

  POP = 'pop'
}